/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as IndexRouteImport } from './routes/index'

const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/initiatives': typeof InitiativesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/testimonials': typeof TestimonialsRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/initiatives': typeof InitiativesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/testimonials': typeof TestimonialsRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/initiatives': typeof InitiativesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/testimonials': typeof TestimonialsRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/initiatives'
    | '/privacy-policy'
    | '/testimonials'
    | '/who-we-are'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/initiatives' | '/privacy-policy' | '/testimonials' | '/who-we-are'
  id:
    | '__root__'
    | '/'
    | '/initiatives'
    | '/privacy-policy'
    | '/testimonials'
    | '/who-we-are'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InitiativesRoute: typeof InitiativesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InitiativesRoute: InitiativesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TestimonialsRoute: TestimonialsRoute,
  WhoWeAreRoute: WhoWeAreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
